# permissions for end users to edit multidimensionalpodautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: multidimensionalpodautoscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mpa-k8s
    app.kubernetes.io/part-of: mpa-k8s
    app.kubernetes.io/managed-by: kustomize
  name: multidimensionalpodautoscaler-editor-role
rules:
- apiGroups:
  - autoscaling.hacker-mpa.io
  resources:
  - multidimensionalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.hacker-mpa.io
  resources:
  - multidimensionalpodautoscalers/status
  verbs:
  - get
