apiVersion: autoscaling.hacker-mpa.io/v1alpha1
kind: MultidimensionalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: mpa-k8s
    app.kubernetes.io/managed-by: kustomize
  name: multidimensionalpodautoscaler-sample
spec:
  # TODO(user): Add fields here
